default: &default
  docker:
  - image: choerodon/cifront:0.5.0

version: 2
jobs:
  node_build_dev:
    <<: *default

    working_directory: ~/repo
    environment:
      CI_PROJECT_PATH: $CIRCLE_PROJECT_REPONAME
    
    steps:
      - checkout
      - run: git submodule update --init
      - run: cd ~/repo/choerodon-front-devops && git submodule update --init
      - run: cd ~/repo/choerodon-front-iam && git submodule update --init
      - run: cd ~/repo/choerodon-front-agile && git submodule update --init
      - run: cd ~/repo
      - run: |
            npm install -registry ${NPM_REPO}
            mkdir -p /cache/$CI_PROJECT_NAME-$CI_PROJECT_ID-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA/
            mkdir -p ./tmp/
            cp -r ./node_modules/choerodon-front-boot/structure/configAuto.py ./tmp/
            mkdir -p ./tmp/iam/src/app/iam/
            cp -r ./choerodon-front-iam/iam/src/app/iam/config ./tmp/iam/src/app/iam/
            mkdir -p ./tmp/devops/src/app/devops/
            cp -r ./choerodon-front-devops/devops/src/app/devops/config ./tmp/devops/src/app/devops/
            mkdir -p ./tmp/agile/src/app/agile/
            cp -r ./choerodon-front-agile/agile/src/app/agile/config ./tmp/agile/src/app/agile/
            cd ./tmp
            python ./configAuto.py iam devops agile
      - run: 
          name: Build modules
          command: |
            chmod -R 777 node_modules
            npm run ${1:-"build"} choerodon-front-iam/iam choerodon-front-devops/devops choerodon-front-agile/agile -registry ${NPM_REPO}
          no_output_timeout: 60m

  node_build:
    <<: *default

    working_directory: ~/repo

    steps:
      - checkout
      - run: git submodule update --init
      - run: cd ~/repo/choerodon-front-devops && git submodule update --init
      - run: cd ~/repo/choerodon-front-iam && git submodule update --init
      - run: cd ~/repo/choerodon-front-agile && git submodule update --init
      - run: cd ~/repo
      - run: |
            npm install -registry ${NPM_REPO}
            mkdir -p ./tmp/
            cp -r ./node_modules/choerodon-front-boot/structure/configAuto.py ./tmp/
            mkdir -p ./tmp/iam/src/app/iam/
            cp -r ./choerodon-front-iam/iam/src/app/iam/config ./tmp/iam/src/app/iam/
            mkdir -p ./tmp/devops/src/app/devops/
            cp -r ./choerodon-front-devops/devops/src/app/devops/config ./tmp/devops/src/app/devops/
            mkdir -p ./tmp/agile/src/app/agile/
            cp -r ./choerodon-front-agile/agile/src/app/agile/config ./tmp/agile/src/app/agile/
            cd ./tmp
            python ./configAuto.py iam devops agile
      - run: 
          name: Build modules
          command: |
            chmod -R 777 node_modules
            npm run ${1:-"build"} choerodon-front-iam/iam choerodon-front-devops/devops choerodon-front-agile/agile -registry ${NPM_REPO}
            find dist -name '*.js' | xargs sed -i "s/localhost:version/$CI_COMMIT_TAG/g"
          no_output_timeout: 60m

      - persist_to_workspace:
          root: .
          paths:
            - dist
            - node_modules/choerodon-front-boot/structure
            - tmp/config.yml
            
  docker_build:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: mv tmp/config.yml ./config.yml
      - run: mv node_modules/choerodon-front-boot/structure ./structure
      - run: |
          sed -i "s/registry\.cn\-hangzhou\.aliyuncs.com\/choerodon-tools/choerodon/g" Dockerfile
          export CI_COMMIT_TAG=$CIRCLE_TAG
          docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
          docker build --pull -t ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}:${CI_COMMIT_TAG} .
          docker push ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}:${CI_COMMIT_TAG}

  helm_chart_build:
    docker:
    - image: choerodon/cibase:0.5.0
    steps:
      - checkout
      - run: |
          export CI_COMMIT_TAG=$(GetVersion)
          CHART_PATH=`find . -name Chart.yaml`
          yq w -i ${CHART_PATH%/*}/values.yaml image.repository ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}
          yq w -i ${CHART_PATH%/*}/values.yaml image.tag ${CI_COMMIT_TAG}
          helm repo add choerodon "${CHART_REPOSITORY}/${CHART_ORGANIZATION}/${CHART_PROJECT}/"
          helm push --username ${HELM_USER} --password ${HELM_PASSWORD} ${CHART_PATH%/*} --version ${CI_COMMIT_TAG} choerodon

workflows:
  version: 2
  release:
    jobs:
      - node_build:
          context: org-global
          filters:
            tags:
              only: /^.*/
            branches:
              only:
                - /^release-.*$/
                - /^hotfix-.*$/
      - docker_build:
          context: org-global
          requires:
          - node_build
          filters:
            tags:
              only: /^.*/
            branches:
              only:
                - /^release-.*$/
                - /^hotfix-.*$/
      - helm_chart_build:
          context: org-global
          requires:
          - node_build
          filters:
            tags:
              only: /^.*/
            branches:
              only:
                - /^release-.*$/
                - /^hotfix-.*$/

  develop:
    jobs:
      - node_build_dev:
          context: org-global
          filters:
            branches:
              only: 
               - /^.*$/