default: &default
  docker:
  - image: choerodon/cifront:0.5.0

version: 2
jobs:
  node_build_dev:
    <<: *default

    working_directory: ~/repo
    environment:
      CI_PROJECT_PATH: $CIRCLE_PROJECT_REPONAME
    
    steps:
      - checkout
      - run: git submodule update --init
      - run: cd ~/repo/choerodon-front-devops && git submodule update --init
      - run: cd ~/repo/choerodon-front-iam && git submodule update --init
      - run: cd ~/repo
      - run: |
            cp -fr ./choerodon-front-devops/devops ./choerodon-front-iam
            cd choerodon-front-iam
            python ./boot/structure/configAuto.py iam devops
            chmod a+x ./boot/structure/moduleCi.sh
            ./boot/structure/moduleCi.sh boot iam devops
      - run: |
            cd choerodon-front-iam/boot
            ./node_modules/.bin/gulp start
            npm run devbuild

  node_build:
    <<: *default

    working_directory: ~/repo

    steps:
      - checkout
      - run: git submodule update --init
      - run: cd ~/repo/choerodon-front-devops && git submodule update --init
      - run: cd ~/repo/choerodon-front-iam && git submodule update --init
      - run: cd ~/repo
      - run: |
            cp -fr ./choerodon-front-devops/devops ./choerodon-front-iam
            cd choerodon-front-iam
            python ./boot/structure/configAuto.py iam devops
            chmod a+x ./boot/structure/moduleCi.sh
            cd boot && npm install choerodon-ui -S  && cd ..
            ./boot/structure/moduleCi.sh boot iam devops
      - run: |
            cd choerodon-front-iam/boot
            ./node_modules/.bin/gulp start
            npm run build
          
      - persist_to_workspace:
          root: .
          paths:
            - choerodon-front-iam/boot/dist
            - choerodon-front-iam/boot/structure
            - choerodon-front-iam/boot/structure
            - choerodon-front-iam/config.yml
            
  docker_build:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: mv choerodon-front-iam/boot/dist ./dist 
      - run: mv choerodon-front-iam/config.yml ./config.yml
      - run: |
          sed -i "s/registry\.cn\-hangzhou\.aliyuncs.com\/choerodon-tools/choerodon/g" Dockerfile
          export CI_COMMIT_TAG=$CIRCLE_TAG
          docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
          docker build --pull -t ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}:${CI_COMMIT_TAG} .
          docker push ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}:${CI_COMMIT_TAG}

  helm_chart_build:
    docker:
    - image: choerodon/cibase:0.5.0
    steps:
      - checkout
      - run: |
          export CI_COMMIT_TAG=$(GetVersion)
          CHART_PATH=`find . -name Chart.yaml`
          yq w -i ${CHART_PATH%/*}/values.yaml image.repository ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}
          yq w -i ${CHART_PATH%/*}/values.yaml image.tag ${CI_COMMIT_TAG}
          helm repo add choerodon "${CHART_REPOSITORY}/${CHART_ORGANIZATION}/${CHART_PROJECT}/"
          helm push --username ${HELM_USER} --password ${HELM_PASSWORD} ${CHART_PATH%/*} --version ${CI_COMMIT_TAG} choerodon

workflows:
  version: 2
  release:
    jobs:
      - node_build:
          context: org-global
          filters:
            tags:
              only: /^.*/
            branches:
              only:
                - /^release-.*$/
                - /^hotfix-.*$/
      - docker_build:
          context: org-global
          requires:
          - node_build
          filters:
            tags:
              only: /^.*/
            branches:
              only:
                - /^release-.*$/
                - /^hotfix-.*$/
      - helm_chart_build:
          context: org-global
          requires:
          - node_build
          filters:
            tags:
              only: /^.*/
            branches:
              only:
                - /^release-.*$/
                - /^hotfix-.*$/

  develop:
    jobs:
      - node_build_dev:
          context: org-global
          filters:
            branches:
              only: 
               - /^.*$/
