default: &default
  docker:
  - image: choerodon/cibase:0.8.1

version: 2
jobs:
  node_build:
    <<: *default

    working_directory: ~/repo

    steps:
      - checkout
      - run: git submodule update --init
      - run: cd ~/repo/choerodon-front-devops && git submodule update --init
      - run: cd ~/repo/choerodon-front-iam && git submodule update --init
      - run: cd ~/repo/choerodon-front-agile && git submodule update --init
      - run: cd ~/repo/choerodon-front-test-manager && git submodule update --init
      - run: cd ~/repo/choerodon-front-wiki && git submodule update --init
      - run: cd ~/repo/choerodon-front-issue && git submodule update --init
      - run: cd ~/repo
      - run:           
          name: Npm Install
          command: |
            modules=(iam devops agile testManager wiki issue)
            folers=(choerodon-front-iam choerodon-front-devops choerodon-front-agile choerodon-front-test-manager choerodon-front-wiki choerodon-front-issue)

            npm i -registry ${NPM_REPO} --sass-binary-site=http://npm.taobao.org/mirrors/node-sass
            mkdir -p ./tmp/
            cp -r ./node_modules/choerodon-front-boot/structure ./tmp/structure
    
            for i in "${!modules[@]}"; 
            do 
              mkdir -p ./tmp/${modules[$i]}/src/app/${modules[$i]}/
              cp -r ./${folers[$i]}/${modules[$i]}/src/app/${modules[$i]}/config ./tmp/${modules[$i]}/src/app/${modules[$i]}/
            done

            cd ./tmp
            python ./structure/menu/__init__.py -o yml -m ${modules[@]}
            python ./structure/dashboard/__init__.py -o yml -m iam devops agile testManager wiki
            cd ..

            npm install -registry ${NPM_REPO}
            mkdir -p ./tmp/
            cp -r ./node_modules/choerodon-front-boot/structure ./tmp/structure
            modules=(iam devops agile testManager wiki issue)
            folers=(choerodon-front-iam choerodon-front-devops choerodon-front-agile choerodon-front-test-manager choerodon-front-wiki choerodon-front-issue)
            for i in "${!modules[@]}"; 
            do 
              mkdir -p ./tmp/${modules[$i]}/src/app/${modules[$i]}/
              cp -r ./${folers[$i]}/${modules[$i]}/src/app/${modules[$i]}/config ./tmp/${modules[$i]}/src/app/${modules[$i]}/
            done
            cd ./tmp
            python ./structure/menu/__init__.py -o yml -m ${modules[@]}
            python ./structure/dashboard/__init__.py -o yml -m iam devops agile testManager wiki
      - run: 
          name: Build modules
          command: |
            chmod -R 777 node_modules
            modules=(choerodon-front-iam/iam choerodon-front-devops/devops choerodon-front-agile/agile choerodon-front-test-manager/testManager choerodon-front-wiki/wiki choerodon-front-issue/issue)
            npm run linux_build ${modules[@]} -registry ${NPM_REPO} --sass-binary-site=http://npm.taobao.org/mirrors/node-sass
            find dist -name '*.js' | xargs sed -i "s/localhost:version/$CIRCLE_TAG/g"
          no_output_timeout: 60m

      - persist_to_workspace:
          root: .
          paths:
            - dist
            - node_modules/choerodon-front-boot/structure
            - tmp/menu.yml
            - tmp/dashboard.yml

  docker_build:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: mv tmp/menu.yml ./menu.yml
      - run: mv tmp/dashboard.yml ./dashboard.yml
      - run: mv node_modules/choerodon-front-boot/structure ./structure
      - run: |
          sed -i "s/registry\.cn\-hangzhou\.aliyuncs.com\/choerodon-tools/choerodon/g" Dockerfile
          docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
          docker build --pull -t ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG} .
          docker push ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}

  helm_chart_build:
    docker:
    - image: choerodon/cibase:0.7.0
    steps:
      - checkout
      - run: |
          CHART_PATH=`find . -name Chart.yaml`
          yq w -i ${CHART_PATH%/*}/values.yaml image.repository ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}
          yq w -i ${CHART_PATH%/*}/values.yaml image.tag ${CIRCLE_TAG}
          helm repo add choerodon "${CHART_REPOSITORY}/${CHART_ORGANIZATION}/${CHART_PROJECT}/"
          helm push --username ${HELM_USER} --password ${HELM_PASSWORD} ${CHART_PATH%/*} --version ${CIRCLE_TAG} choerodon

workflows:
  version: 2
  release:
    jobs:
      - node_build:
          context: org-global
          filters:
            tags:
              only: /^.*/
            branches:
              only:
                - /^release-.*$/
                - /^hotfix-.*$/
      - docker_build:
          context: org-global
          requires:
          - node_build
          filters:
            tags:
              only: /^.*/
            branches:
              only:
                - /^release-.*$/
                - /^hotfix-.*$/
      - helm_chart_build:
          context: org-global
          requires:
          - node_build
          filters:
            tags:
              only: /^.*/
            branches:
              only:
                - /^release-.*$/
                - /^hotfix-.*$/