apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-config
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
  labels:
{{ include "service.labels.standard" . | indent 4 }}
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 120
  template:
    metadata:
      name: {{ .Release.Name }}-init-config
    spec:
      containers:
      - name: {{ .Release.Name }}-init-config
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: DB_HOST
          value: {{ .Values.preJob.preConfig.mysql.host }}
        - name: DB_PORT
          value: {{ .Values.preJob.preConfig.mysql.port | quote }}
        - name: DB_USER
          value: {{ .Values.preJob.preConfig.mysql.username }}
        - name: DB_PASS
          value: {{ .Values.preJob.preConfig.mysql.password }}
        - name: DB_NAME
          value: {{ .Values.preJob.preConfig.mysql.dbname }}
        - name: UP_ATTRS
          value: {{ .Values.preJob.preConfig.mysql.upattrs }}
        command:
        - /bin/sh
        - -c
        - '
          cd /usr/share/nginx/html;
          python sql.py -d {{ .Values.preJob.preConfig.mysql.enabledelete }};
          python initDir.py dirMenu.yml;
          '
      restartPolicy: Never